set -g mouse on

set -s set-clipboard on

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key -n M-h select-pane -L
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U
bind-key -n M-l select-pane -R

bind-key -n M-H select-pane -L \; swap-pane -s '!'
bind-key -n M-J select-pane -D \; swap-pane -s '!'
bind-key -n M-K select-pane -U \; swap-pane -s '!'
bind-key -n M-L select-pane -R \; swap-pane -s '!'

bind-key -n M-r switch-client -T resize-mode
bind-key -T resize-mode h resize-pane -L 1 \; switch-client -T resize-mode
bind-key -T resize-mode j resize-pane -D 1 \; switch-client -T resize-mode
bind-key -T resize-mode k resize-pane -U 1 \; switch-client -T resize-mode
bind-key -T resize-mode l resize-pane -R 1 \; switch-client -T resize-mode

bind-key -n M-% split-window -h -c "#{pane_current_path}"
bind-key -n M-\" split-window -v -c "#{pane_current_path}"

bind-key -n M-c new-window
bind-key -n M-x confirm kill-pane
bind-key -n M-f resize-pane -Z

bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9
